name = "nada"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/main.py"
prime_size = 128


[[programs]]
path = "src/secret_addition.py"
name = "secret_addition"
prime_size = 128

[[programs]]
path = "src/medical_research.py"
name = "medical_research"
prime_size = 128
